### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [ar-siddiqui/curve_number_generator#1]
Can you please upload the source code into this repository and add a proper homepage link in metadata.txt

**Comment by someone191** [comment]
*Just did both. Please check now. Thanks*

**Comment by ar-siddiqui** [comment]
Hi @NyakudyaA Is there a way to change my QGIS ID name? I talked to OSGeo people they said no it can't be changed.
If that is not possible, I would like to create a new account and change ownership of the plugin to that new account. Do you know how will that be executed?

**Comment by NyakudyaA** [comment]
From QGIS side I can change ownership of the plugin. You just notify me of the new credentials
