### ISSUE TITLE
NLCD Server Down

### ISSUE THREAD

**Issue by FLO-2DKaren** [ar-siddiqui/curve_number_generator#29]
It looks like a change was applied to the GEOS  GeoServer 
jms-cluster: switch to using managed dependency for log4j

Now the Curve_number_generator may not be getting downloads.

Here is the Log Message:
QGIS version: 3.18.2-Zürich
QGIS code revision: 515138c171
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Curve Number Generator' starting…
Input parameters:
{ 'OutputCurveNumberLayer' : True, 'OutputNLCDImperviousRaster' : True, 'OutputNLCDLandCoverRaster' : True, 'OutputNLCDLandCoverVector' : False, 'OutputSoilLayer' : True, 'areaboundary' : 'D:/FLO-2D Docs/Short Course/AFMA 2021/Advanced Class/Module 1/Lesson 1.gpkg|layername=grid', 'cnlookup' : None, 'drainedsoilsleaveuncheckedifnotsure' : False }

Area Boundary layer extent area is 1,273.9463 acres

Successfully downloaded https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2019_Impervious_L48/ows?version=1.3.0&service=WMS&layers=NLCD_2019_Impervious_L48&styles&crs=EPSG:2223&format=image/geotiff&request=GetMap&width=279&height=221&BBOX=656965.3593088828,957270.0,665335.3593088828,963900.0&
Results: {'OUTPUT': 'C:/Users/ComuterName/AppData/Local/Temp/processing_tpjsop/a9cb30bd23e84eb59afa4a9035c9b814/OUTPUT.file.0&'}
Unable to execute algorithm
Incorrect parameter value for INPUT
Unable to execute algorithm
Could not load source layer for INPUT: C:/Users//ComuterName/AppData/Local/Temp/processing_tpjsop/a9cb30bd23e84eb59afa4a9035c9b814/OUTPUT.file.0& not found
Unable to execute algorithm
Could not load source layer for INPUT: C:/Users//ComuterName/AppData/Local/Temp/processing_tpjsop/a9cb30bd23e84eb59afa4a9035c9b814/OUTPUT.file.0& not found
Execution failed after 1.82 seconds

Loading resulting layers
Algorithm 'Curve Number Generator' finished

**Comment by ar-siddiqui** [comment]
@FLO-2DKaren I am not able to download data from NLCD using any method, tried QGIS WMS, Postman, WCS. 
It looks like their server is down.

Is there anything the CN plugin can do other than report a user-friendly message if this happens again?

**Comment by FLO-2DKaren** [comment]
@ar-siddiqui Hi Abdul,  I noticed that it was down too after I posted this.  I wrote in an email to their contact form.  I hope that helps.  I think an error message would be a simple solution.
