### ISSUE TITLE
SSL Certificate Issues

### ISSUE THREAD

**Issue by GAustinCorbett** [ar-siddiqui/curve_number_generator#31]
Tried running the plugin tool with QGIS 3.18.3-Zurich on Windows 10.

On the initial run, an error popped up regarding some type of SSL Certificate issue.  I hit "ignore", but not "ignore and save".  The tool failed because it couldn't pull the data down.  On subsequent runs, the pop-up wouldn't open but the tool still wouldn't work.  I uninstalled and reinstalled the plugin, still no popup, still no success.  The error message indicated that it was on the server side, but I guessed this was a client-side issue.

I was able to fix this by manually creating an certificate exception under Settings > options > Authentication > Manage Certificates > Servers (tab) and created one for www.mrlc.gov.  I wasn't sure which errors needed to be ignored so I checked essentially all of them. 

Tool then ran fine. 

Also, let me just say, thanks a ton for creating this! You are a selfless human saving people many human-hours of frustration.

**Comment by ar-siddiqui** [comment]
Hey, thanks for appreciation. I am aware of this issue, the main issue is on the server side (SSL certification), there are some ways to bypass it like how you did, but I haven't had a consistent solution that will work every time and that can be implemented in the plugin itself. The certificate issue usually resolves on the www.mrlc.gov in few hours and is very rare, so I am not sure what (should anything) can be done on the client-side. Ideas welcome!
