### ISSUE TITLE
Data type issue when applying user-defined CN table

### ISSUE THREAD

**Issue by yhan27** [ar-siddiqui/curve_number_generator#45]
I observed one thing that I want a clarification.

1. If I use the default CN look up table, the cn field of the generated cn shapefile is in decimal; this is good since I can rasterize it easily;
2. However, I use my own CN look up table, the cn field of the generated cn shapefile is a text string; is this a bug? I would like the field is still in decimal under this situation.

**Comment by ar-siddiqui** [comment]
Please try adding a `.csvt` file beside your CSV like this. That should solve the issue. 
![image](https://user-images.githubusercontent.com/53625184/197014674-789d4766-d816-46d8-911f-f96a0f9b9f2e.png)
