### ISSUE TITLE
Custom Algorithm removes underscore from grid_code csv during processing, cn field returns Null

### ISSUE THREAD

**Issue by bthomasBRP** [ar-siddiqui/curve_number_generator#47]
When trying to run the custom algorithm, the "_" is removed from the grid_code column.  I think this may be causing an issue where the cn field returned is Null.  This occurs even when using the NLCD, Soils, and default cn lookup table created in the standard algorithm.

![image](https://user-images.githubusercontent.com/126486547/221589074-61f42462-2e84-4511-8512-842fb4f768ed.png)

**Comment by ar-siddiqui** [comment]
@bthomasBRP The formula for the custom algorithm was missing `_`. I fixed it, can you download the fixed plugin from here and test it with your data.

https://github.com/ar-siddiqui/curve_number_generator/tree/hotfix/custom-algorithm-formula/curve_number_generator

You will have to download this folder and replace curve_number_generator folder in your QGIS plugins folder, then restart QGIS and test.

**Comment by bthomasBRP** [comment]
Thanks for working on this!  I can confirm that this update corrected the issue that I was running into and will be able to utilize the tool for proposed land cover changes.  One thing to note for other users that may want to use the custom algorithm, you will have to create a custom soil field that handles the dual class HSG types.  The custom algorithm will generate an error for the grid_code if the string length is greater than 5.  
![image](https://user-images.githubusercontent.com/126486547/226712992-66ee628d-eea2-4e89-9637-7713e43b0ab1.png)

**Comment by ar-siddiqui** [comment]
Thanks for noticing the 5-character limit, you are right, the idea behind the custom algorithm is that the user should pre-process the soil layer to not contain any nulls or dual soil types, etc. But the soil doesn't need to be HSG only, it can be a different dataset as well, hence I removed the 5 characters limit.
